language: scala

jdk:
  - oraclejdk8

env:
  - JAVA_OPTS="-Dsbt.log.noformat=true"

scala:
  - 2.11.7

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION
    - $HOME/.gitshas
